config/routes.rb
Bakarvids::Application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks" }

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  
  get "video/:caption", to: 'videos#show'
  post "videos/delete_fb_post", to: "videos#delete_fb_post"
  post "videos/update_fb_post", to: "videos#update_fb_post"
  match 'auth/:provider/callback', to: 'videos#twitter'
  post '/suggest_video', to: 'videos#suggest'
  post '/subscribe', to: 'videos#subscribe'
  match '/search', to: 'videos#search'
  match '/contact', to: 'videos#contact'

  match "privacy", to: "static#privacy"
  match "tos", to: "static#tos"

  resources :videos do
    collection do
      post 'toggle_social'
    end
  end
  match "videos/page/:page", to: 'videos#list'
  match "videos/postfb", to: 'videos#post_on_fb', as: :post_on_fb

  root :to => 'videos#index'

end

app/views/layouts/_footer.html.erb
<div class="navbar" id="footer">
  <div class="navbar-inner">
    <div class="container-fluid">
      <!-- <a class="brand" href="#">Bakarvids</a> -->
      <div class="container-fluid" id="footer-items">
        <ul class="nav">
          <li><%= link_to_function "&copy; Bakarvids".html_safe, "return false;" %></li>
          <li><%= link_to "Advertise", "/path2"  %></li>
          <li><%= link_to "Privacy", "/privacy.html"  %></li>
          <li><%= link_to "Terms", "/privacy.html"  %></li>
          <li><%= link_to "Contact Us", nil, :id => "contact-bakar" %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <!-- <a class="brand" href="#">Bakarvids</a> -->
          <div class="container nav-collapse" id="header-items">
            <ul class="unstyled pull-left">
              <li style="margin-top: 15px">
                <%= link_to "BakarVids", root_path, :style => "font-size: 32px;font-weight: bold;
text-decoration: none; color: #BFBFBF" %>
              </li>
            </ul>
            <ul class="unstyled search-form pull-right">
              <li>
                <form method="get" action="/search" class="navbar-search">
                  <input type="text" name='name' class="search-query" placeholder="Search">
                </form>
              </li>
            </ul>
            <ul class="nav pull-right">
              <li>
                <% if user_signed_in? %>
                <%= image_tag current_user.profile_image , :class => 'fb-profile-image'%>
                <%= link_to "Sign out", destroy_session_path(current_user), :method => :delete, :class => "fb-signin" %>
                <% else %>
                <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) , :class => "fb-signin"%>
                <% end %>
              </li>
              <li><%= link_to "Subscribe", "javascript://", :id => "subscribe-news"  %></li>
              <li><%= link_to "Suggest A Video", "javascript://", :id => "suggest-video"  %></li>
              <% if current_user %>
              <li  class="clearfix"><%= link_to "Social", "/path2", :id => 'shareToggleLink', :style => "float:left"  %><%= render "layouts/switch" %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <!-- <div class="subnav" id="subnav-bakar">
        <ul class="nav nav-pills">
          <li class="active"><a href="#everything">Everything</a></li>
          <li><a href="#popular">Most Popular</a></li>
          <li><a href="#funny">Funny</a></li>
          <li><a href="#technology">Technology</a></li>
          <li><a href="#ploitics">Ploitics</a></li>
          <li style="float:right"><a href="#suggest" style="border-left: 1px solid #E5E5E5;">Suggest Video</a></li>
        </ul>
    </div> -->
    

app/views/layouts/_social_buttons.html.erb
<div class="social-buttons">

	<a href="https://twitter.com/share" class="twitter-share-button" data-text="I watched an awesome video on #bakarvids. Check this out <%= request.url %>" data-count="none">Tweet</a>
	
</div>

<%= content_for :end_body do %>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
	</script>
<% end %>

app/views/layouts/_switch.html.erb
<div class='on-off <%= "main-on" if current_user.sharing_mode %>' style="float:left">
<span class='switch' <%= "style='left: 35px'" if current_user.sharing_mode %>></span>
<div class='on'>
  <span <%= "style='right: 0px'" if current_user.sharing_mode %>>ON</span>
</div>
<span class='off'>OFF</span>
<input type='checkbox'/>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
   <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# video: http://ogp.me/ns/video#">
    <%= favicon_link_tag "/favicon.ico" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Awesome Handpicked Desi Videos" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield(:head) %>
    <meta name='description' content="<%= content_for(:meta_description) ? yield(:meta_description) : 'Bakarvids brings you awesome handpicked desi videos from all over.' %>" />
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <%= render "layouts/header"%>
    <div class="container" id="top-container-bakar">
      <div class="row">
        <div class="span10 offset1" id="container-outer-bakar" >
          <% if params[:alert] || params[:notice]%>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->
    <div style="width: 100%; height: 60px;"></div>
      <%= render "layouts/footer"%>
        <!-- <p>&copy; Company 2012</p> -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield(:js) %>
    <script type="text/javascript">
      jQuery(document).ready(function($) {
        $("#subscribe-news").click(function(){
          $('#subscribeModal').modal('show');
            return false;
        });

        $("#suggest-video").click(function(){
           $('#suggestVideoModal').modal('show');
            return false;
        });

        $("#contact-bakar").click(function(){
           $('#contactBakarModal').modal('show');
            return false;
        });
      });
      
    </script>
    <div class="modal hide fade" id="subscribeModal">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h2>SUBSCRIBE TO DAILY VIDEO FEED</h2>
      </div>
      <div class="modal-body" style="text-align: center">
        <form method="post" action="/subscribe" class="form-inline">
          <input name="email" type="text" class="input-large" placeholder="Email">
          <button type="submit" class="btn">Subscribe</button>
        </form>
      </div>
      </div>
    </div>

    <div class="modal hide fade" id="contactBakarModal">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h2>Contact Bakarvids</h2>
      </div>
      <div class="modal-body" style="text-align: center">
        <form method="post" action="/contact" class="form-inline">
          <input type="text" name="name" class="input-large" placeholder="Name"><br /><br />
          <input type="text" name="email" class="input-large" placeholder="Email"><br /><br />
          <textarea type="text" name="message" class="input-large" placeholder="Message"></textarea><br /><br />
          <button type="submit" class="btn">Contact</button>
        </form>
      </div>
      </div>
    </div>

    <div class="modal hide fade" id="suggestVideoModal">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h2>SUGGEST A VIDEO</h2>
      </div>
      <div class="modal-body" style="text-align: center">
        <form method="post" action="/suggest_video" class="form-inline">
          <input type="text" name="url" class="input-large" placeholder="Url">
          <button type="submit" class="btn">Go</button>
        </form>
      </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/page.html.erb
  <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bakarvids" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield(:head) %>
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <%= render "layouts/header"%>

    <div class="container">
      <div class="row">
        <div class="span10 offset1" >
          <% if params[:alert] || params[:notice]%>
            <p class="notice"><%= params[:alert] %></p>
            <p class="alert"><%= params[:notice] %></p>
            <p class="alert"><%= params[:error] %></p>
          <% end %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->
    <%= render "layouts/footer"%>

    

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield(:js) %>
    <%= yield(:end_body) %>

    <script type="text/javascript">
      jQuery(document).ready(function($) {
        $("#subscribe-news").click(function(){
          $('#subscribeModal').modal('show');
            return false;
        });

        $("#suggest-video").click(function(){
           $('#suggestVideoModal').modal('show');
            return false;
        });

        $("#contact-bakar").click(function(){
           $('#contactBakarModal').modal('show');
            return false;
        });
      });
      
    </script>


    <div class="modal hide fade" id="subscribeModal">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h2>SUBSCRIBE TO DAILY VIDEO FEED</h2>
      </div>
      <div class="modal-body" style="text-align: center">
        <form method="post" action="/subscribe" class="form-inline">
          <input name="email" type="text" class="input-large" placeholder="Email">
          <button type="submit" class="btn">Subscribe</button>
        </form>
      </div>
      </div>
    </div>

    <div class="modal hide fade" id="contactBakarModal">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h2>Contact Bakarvids</h2>
      </div>
      <div class="modal-body" style="text-align: center">
        <form method="post" action="/contact" class="form-inline">
          <input type="text" name="name" class="input-large" placeholder="Name"><br /><br />
          <input type="text" name="email" class="input-large" placeholder="Email"><br /><br />
          <textarea type="text" name="message" class="input-large" placeholder="Message"></textarea><br /><br />
          <button type="submit" class="btn">Contact</button>
        </form>
      </div>
      </div>
    </div>

    <div class="modal hide fade" id="suggestVideoModal">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h2>SUGGEST A VIDEO</h2>
      </div>
      <div class="modal-body" style="text-align: center">
        <form method="post" action="/suggest_video" class="form-inline">
          <input type="text" name="url" class="input-large" placeholder="Url">
          <button type="submit" class="btn">Go</button>
        </form>
      </div>
      </div>
    </div>
  </body>
</html>